### ISSUE TITLE
Template Inheritance

### ISSUE THREAD

**Issue by RobotGyal** [RobotGyal/ZANK#16]
Implement template inheritance for routes

**Comment by UPstartDeveloper** [comment]
Hey @KabsaA please let me know when you complete making the base template (and extending it to the other templates is optional)!

Then we can work together on making sure the templates are as DRY as possible, in addition then we do cool stuff in Jinja such as adding specialized navbars based on auth!

**Comment by RobotGyal** [comment]
implemented
