### ISSUE TITLE
Browser discrepencies

### ISSUE THREAD

**Issue by RobotGyal** [RobotGyal/ZANK#36]
Works for Chrome but not Safari

**Comment by UPstartDeveloper** [comment]
Fixed in the latest deployment. It was totally my fault guys - I forgot to set the values of the environment variables for Heroku to be able to work with AWS S3:
- ```AWS_ACCESS_KEY_ID```
- ```AWS_SECRET_ACCESS_KEY```
- ```AWS_STORAGE_BUCKET_NAME```
